language: c

before_install:
 - sudo apt-get -y update
 - sudo apt-get -y install linux-headers-generic
 - git submodule update --init

before_script:
 - export RTE_SDK=$(pwd)/dpdk
 - export RTE_TARGET=build

script:
 - ./buildrump.sh/buildrump.sh -T rumptools -s rumpsrc -V MKPIC=no -qq -j16 checkout fullbuild
 - sudo ln -sf $(ls /lib/modules | sed 1q) /lib/modules/$(uname -r)
 - (cd dpdk ; make T=x86_64-default-linuxapp-gcc config && make )
 - ( cd src/libdpdkif; ../../rumptools/rumpmake dependall && ../../rumptools/rumpmake install )
 - (cd examples/tcp_http_get ; make )
 - (cd examples/udp_echo_server ; make )
